AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/MixinUsage:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NumberedParametersLimit:
  Enabled: false
